using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using System.Linq;
using DG.Tweening;

public class TutorialManager : MonoBehaviour
{
    public RectTransform tutorialTextArea;
    public TextMeshProUGUI TutorialTitle;
    public TextMeshProUGUI TutorialText;

    // ï¿½`ï¿½ï¿½ï¿½[ï¿½gï¿½ï¿½ï¿½Aï¿½ï¿½ï¿½^ï¿½Xï¿½N
    protected ITutorialTask currentTask;
    protected List<ITutorialTask> tutorialTask;

    // ï¿½`ï¿½ï¿½ï¿½[ï¿½gï¿½ï¿½ï¿½Aï¿½ï¿½ï¿½\ï¿½ï¿½ï¿½tï¿½ï¿½ï¿½O
    //private bool isEnabled;

    // ï¿½`ï¿½ï¿½ï¿½[ï¿½gï¿½ï¿½ï¿½Aï¿½ï¿½ï¿½^ï¿½Xï¿½Nï¿½Ìï¿½ï¿½ï¿½ï¿½ğ–‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Û‚Ì‘Jï¿½Ú—pï¿½tï¿½ï¿½ï¿½O
    private bool task_executed = false;

    // ï¿½`ï¿½ï¿½ï¿½[ï¿½gï¿½ï¿½ï¿½Aï¿½ï¿½ï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½UIï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½
    private float fade_pos_x = 460;

    private float fade_pos_y = 90;

    [SerializeField]
    private bool tutorialFlag;

    [SerializeField]
    private GameObject obj;

    void Start()
    {
        // è§£åƒåº¦ã§ç§»å‹•è·é›¢ã‚’å¤‰æ›´ã™ã‚‹
        fade_pos_x = 460 * Screen.width / 480;
        fade_pos_y = 90 * Screen.height/ 800;
        
        
        tutorialFlag = ES3.Load<bool>("Tutorial");
        // ï¿½`ï¿½ï¿½ï¿½[ï¿½gï¿½ï¿½ï¿½Aï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ê‡
        if (tutorialFlag)
        {
            tutorialTextArea.GetComponent<CanvasGroup>().alpha = 0;
            return;
        }


        // ï¿½`ï¿½ï¿½ï¿½[ï¿½gï¿½ï¿½ï¿½Aï¿½ï¿½ï¿½Ìˆê——
        tutorialTask = new List<ITutorialTask>()
        {
            new MovementTask(),
            new JumpTask(),
            new EndTask(),
            
        };

        // ï¿½Åï¿½ï¿½Ìƒ`ï¿½ï¿½ï¿½[ï¿½gï¿½ï¿½ï¿½Aï¿½ï¿½ï¿½ï¿½İ’ï¿½
        StartCoroutine(SetCurrentTask(tutorialTask.First()));
    }

    void Update()
    {
        // ï¿½`ï¿½ï¿½ï¿½[ï¿½gï¿½ï¿½ï¿½Aï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½İ‚ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½È‚ï¿½ï¿½ê‡ï¿½Éï¿½ï¿½ï¿½
        if (currentTask != null && !task_executed)
        {
            // ï¿½ï¿½ï¿½İ‚Ìƒ`ï¿½ï¿½ï¿½[ï¿½gï¿½ï¿½ï¿½Aï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½ï¿½ê‚½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            if (currentTask.CheckTask())
            {
                task_executed = true;

                DOVirtual.DelayedCall(currentTask.GetTransitionTime(), () => {
                    iTween.MoveTo(tutorialTextArea.gameObject, iTween.Hash(
                        "position", tutorialTextArea.transform.position + new Vector3(fade_pos_x, 0, 0),
                        "time", 1f
                    ));
                    tutorialTask.RemoveAt(0);

                    var nextTask = tutorialTask.FirstOrDefault();
                    if (nextTask != null)
                    {
                        StartCoroutine(SetCurrentTask(nextTask, 1f));
                    }
                    else
                    {
                        tutorialFlag = true;
                    }
                });
            }
        }

    }

    public bool CheckTutorialEnd()
	{
        return tutorialFlag;
    }

    /// <summary>
    /// ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½`ï¿½ï¿½ï¿½[ï¿½gï¿½ï¿½ï¿½Aï¿½ï¿½ï¿½^ï¿½Xï¿½Nï¿½ï¿½İ’è‚·ï¿½ï¿½
    /// </summary>
    /// <param name="task"></param>
    /// <param name="time"></param>
    /// <returns></returns>
    protected IEnumerator SetCurrentTask(ITutorialTask task, float time = 0)
    {
        // timeï¿½ï¿½ï¿½wï¿½è‚³ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ê‡ï¿½Í‘Ò‹@
        yield return new WaitForSeconds(time);

        currentTask = task;
        task_executed = false;

        // UIï¿½Éƒ^ï¿½Cï¿½gï¿½ï¿½ï¿½Æï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½İ’ï¿½
        TutorialTitle.text = task.GetTitle();
        TutorialText.text = task.GetText();

        // ï¿½`ï¿½ï¿½ï¿½[ï¿½gï¿½ï¿½ï¿½Aï¿½ï¿½ï¿½^ï¿½Xï¿½Nï¿½İ’èï¿½pï¿½ÌŠÖï¿½ï¿½ï¿½ï¿½ï¿½ï¿½s
        task.OnTaskSetting();

        iTween.MoveTo(tutorialTextArea.gameObject, iTween.Hash(
            "position", tutorialTextArea.transform.position - new Vector3(fade_pos_x, 0, 0),
            "time", 1f
        ));
    }

    /// <summary>
    /// ç‰¹ã«ä½¿ã£ã¦ã„ãªã„
    /// </summary>
    protected void SwitchEnabled()
    {
        //isEnabled = !isEnabled;

        // UIï¿½Ì•\ï¿½ï¿½ï¿½Ø‚ï¿½Ö‚ï¿½
        //float alpha = isEnabled ? 1f : 0;
        //tutorialTextArea.GetComponent<CanvasGroup>().alpha = alpha;
    }
}
